/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TimeridImport } from './routes/$timer_id'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TimeridRoute = TimeridImport.update({
  id: '/$timer_id',
  path: '/$timer_id',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$timer_id': {
      id: '/$timer_id'
      path: '/$timer_id'
      fullPath: '/$timer_id'
      preLoaderRoute: typeof TimeridImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$timer_id': typeof TimeridRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$timer_id': typeof TimeridRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$timer_id': typeof TimeridRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$timer_id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$timer_id'
  id: '__root__' | '/' | '/$timer_id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimeridRoute: typeof TimeridRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimeridRoute: TimeridRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$timer_id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$timer_id": {
      "filePath": "$timer_id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
